services:
  pismo-challenge-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    volumes:
      - .:/go/src/app
    ports:
      - "8080:8080"
    env_file:
      - .app.env
    depends_on:
      - pismo-challenge-db

    
  pismo-migrations:
    build:
      context: .
      dockerfile: Dockerfile
      target: migrations
    volumes:
      - ./migrations/:/migrations
    env_file:
      - .app.env
    depends_on:
      - pismo-challenge-app
    
  pismo-challenge-db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .app.env
    networks:
      - default
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: