// Code generated by MockGen. DO NOT EDIT.
// Source: src/application/ports/account.go

// Package mock_ports is a generated GoMock package.
package mock_ports

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/rodrigocardosodev/pismo-challenge/src/application/models"
)

// MockIAccountReader is a mock of IAccountReader interface.
type MockIAccountReader struct {
	ctrl     *gomock.Controller
	recorder *MockIAccountReaderMockRecorder
}

// MockIAccountReaderMockRecorder is the mock recorder for MockIAccountReader.
type MockIAccountReaderMockRecorder struct {
	mock *MockIAccountReader
}

// NewMockIAccountReader creates a new mock instance.
func NewMockIAccountReader(ctrl *gomock.Controller) *MockIAccountReader {
	mock := &MockIAccountReader{ctrl: ctrl}
	mock.recorder = &MockIAccountReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAccountReader) EXPECT() *MockIAccountReaderMockRecorder {
	return m.recorder
}

// GetByDocumentNumber mocks base method.
func (m *MockIAccountReader) GetByDocumentNumber(ctx context.Context, documentNumber string) (models.AccountInterface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByDocumentNumber", ctx, documentNumber)
	ret0, _ := ret[0].(models.AccountInterface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByDocumentNumber indicates an expected call of GetByDocumentNumber.
func (mr *MockIAccountReaderMockRecorder) GetByDocumentNumber(ctx, documentNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByDocumentNumber", reflect.TypeOf((*MockIAccountReader)(nil).GetByDocumentNumber), ctx, documentNumber)
}

// GetByID mocks base method.
func (m *MockIAccountReader) GetByID(ctx context.Context, id int64) (models.AccountInterface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(models.AccountInterface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockIAccountReaderMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockIAccountReader)(nil).GetByID), ctx, id)
}

// MockIAccountWriter is a mock of IAccountWriter interface.
type MockIAccountWriter struct {
	ctrl     *gomock.Controller
	recorder *MockIAccountWriterMockRecorder
}

// MockIAccountWriterMockRecorder is the mock recorder for MockIAccountWriter.
type MockIAccountWriterMockRecorder struct {
	mock *MockIAccountWriter
}

// NewMockIAccountWriter creates a new mock instance.
func NewMockIAccountWriter(ctrl *gomock.Controller) *MockIAccountWriter {
	mock := &MockIAccountWriter{ctrl: ctrl}
	mock.recorder = &MockIAccountWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAccountWriter) EXPECT() *MockIAccountWriterMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIAccountWriter) Create(ctx context.Context, account models.AccountInterface) (models.AccountInterface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, account)
	ret0, _ := ret[0].(models.AccountInterface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIAccountWriterMockRecorder) Create(ctx, account interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIAccountWriter)(nil).Create), ctx, account)
}

// MockIAccountRepository is a mock of IAccountRepository interface.
type MockIAccountRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIAccountRepositoryMockRecorder
}

// MockIAccountRepositoryMockRecorder is the mock recorder for MockIAccountRepository.
type MockIAccountRepositoryMockRecorder struct {
	mock *MockIAccountRepository
}

// NewMockIAccountRepository creates a new mock instance.
func NewMockIAccountRepository(ctrl *gomock.Controller) *MockIAccountRepository {
	mock := &MockIAccountRepository{ctrl: ctrl}
	mock.recorder = &MockIAccountRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAccountRepository) EXPECT() *MockIAccountRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIAccountRepository) Create(ctx context.Context, account models.AccountInterface) (models.AccountInterface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, account)
	ret0, _ := ret[0].(models.AccountInterface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIAccountRepositoryMockRecorder) Create(ctx, account interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIAccountRepository)(nil).Create), ctx, account)
}

// GetByDocumentNumber mocks base method.
func (m *MockIAccountRepository) GetByDocumentNumber(ctx context.Context, documentNumber string) (models.AccountInterface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByDocumentNumber", ctx, documentNumber)
	ret0, _ := ret[0].(models.AccountInterface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByDocumentNumber indicates an expected call of GetByDocumentNumber.
func (mr *MockIAccountRepositoryMockRecorder) GetByDocumentNumber(ctx, documentNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByDocumentNumber", reflect.TypeOf((*MockIAccountRepository)(nil).GetByDocumentNumber), ctx, documentNumber)
}

// GetByID mocks base method.
func (m *MockIAccountRepository) GetByID(ctx context.Context, id int64) (models.AccountInterface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(models.AccountInterface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockIAccountRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockIAccountRepository)(nil).GetByID), ctx, id)
}
