// Code generated by MockGen. DO NOT EDIT.
// Source: src/application/ports/transaction.go

// Package mock_ports is a generated GoMock package.
package mock_ports

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/rodrigocardosodev/pismo-challenge/src/application/models"
)

// MockITransactionWriter is a mock of ITransactionWriter interface.
type MockITransactionWriter struct {
	ctrl     *gomock.Controller
	recorder *MockITransactionWriterMockRecorder
}

// MockITransactionWriterMockRecorder is the mock recorder for MockITransactionWriter.
type MockITransactionWriterMockRecorder struct {
	mock *MockITransactionWriter
}

// NewMockITransactionWriter creates a new mock instance.
func NewMockITransactionWriter(ctrl *gomock.Controller) *MockITransactionWriter {
	mock := &MockITransactionWriter{ctrl: ctrl}
	mock.recorder = &MockITransactionWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITransactionWriter) EXPECT() *MockITransactionWriterMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockITransactionWriter) Create(ctx context.Context, Transaction models.TransactionInterface) (models.TransactionInterface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, Transaction)
	ret0, _ := ret[0].(models.TransactionInterface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockITransactionWriterMockRecorder) Create(ctx, Transaction interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockITransactionWriter)(nil).Create), ctx, Transaction)
}

// MockITransactionReader is a mock of ITransactionReader interface.
type MockITransactionReader struct {
	ctrl     *gomock.Controller
	recorder *MockITransactionReaderMockRecorder
}

// MockITransactionReaderMockRecorder is the mock recorder for MockITransactionReader.
type MockITransactionReaderMockRecorder struct {
	mock *MockITransactionReader
}

// NewMockITransactionReader creates a new mock instance.
func NewMockITransactionReader(ctrl *gomock.Controller) *MockITransactionReader {
	mock := &MockITransactionReader{ctrl: ctrl}
	mock.recorder = &MockITransactionReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITransactionReader) EXPECT() *MockITransactionReaderMockRecorder {
	return m.recorder
}

// GetBalanceByAccountID mocks base method.
func (m *MockITransactionReader) GetBalanceByAccountID(ctx context.Context, accountId int64) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalanceByAccountID", ctx, accountId)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalanceByAccountID indicates an expected call of GetBalanceByAccountID.
func (mr *MockITransactionReaderMockRecorder) GetBalanceByAccountID(ctx, accountId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalanceByAccountID", reflect.TypeOf((*MockITransactionReader)(nil).GetBalanceByAccountID), ctx, accountId)
}

// MockITransactionRepository is a mock of ITransactionRepository interface.
type MockITransactionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockITransactionRepositoryMockRecorder
}

// MockITransactionRepositoryMockRecorder is the mock recorder for MockITransactionRepository.
type MockITransactionRepositoryMockRecorder struct {
	mock *MockITransactionRepository
}

// NewMockITransactionRepository creates a new mock instance.
func NewMockITransactionRepository(ctrl *gomock.Controller) *MockITransactionRepository {
	mock := &MockITransactionRepository{ctrl: ctrl}
	mock.recorder = &MockITransactionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITransactionRepository) EXPECT() *MockITransactionRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockITransactionRepository) Create(ctx context.Context, Transaction models.TransactionInterface) (models.TransactionInterface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, Transaction)
	ret0, _ := ret[0].(models.TransactionInterface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockITransactionRepositoryMockRecorder) Create(ctx, Transaction interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockITransactionRepository)(nil).Create), ctx, Transaction)
}

// GetBalanceByAccountID mocks base method.
func (m *MockITransactionRepository) GetBalanceByAccountID(ctx context.Context, accountId int64) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalanceByAccountID", ctx, accountId)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalanceByAccountID indicates an expected call of GetBalanceByAccountID.
func (mr *MockITransactionRepositoryMockRecorder) GetBalanceByAccountID(ctx, accountId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalanceByAccountID", reflect.TypeOf((*MockITransactionRepository)(nil).GetBalanceByAccountID), ctx, accountId)
}
