// Code generated by MockGen. DO NOT EDIT.
// Source: src/application/models/account.go

// Package mock_models is a generated GoMock package.
package mock_models

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAccountInterface is a mock of AccountInterface interface.
type MockAccountInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAccountInterfaceMockRecorder
}

// MockAccountInterfaceMockRecorder is the mock recorder for MockAccountInterface.
type MockAccountInterfaceMockRecorder struct {
	mock *MockAccountInterface
}

// NewMockAccountInterface creates a new mock instance.
func NewMockAccountInterface(ctrl *gomock.Controller) *MockAccountInterface {
	mock := &MockAccountInterface{ctrl: ctrl}
	mock.recorder = &MockAccountInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountInterface) EXPECT() *MockAccountInterfaceMockRecorder {
	return m.recorder
}

// GetAmount mocks base method.
func (m *MockAccountInterface) GetAmount() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAmount")
	ret0, _ := ret[0].(int64)
	return ret0
}

// GetAmount indicates an expected call of GetAmount.
func (mr *MockAccountInterfaceMockRecorder) GetAmount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAmount", reflect.TypeOf((*MockAccountInterface)(nil).GetAmount))
}

// GetDocumentNumber mocks base method.
func (m *MockAccountInterface) GetDocumentNumber() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDocumentNumber")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetDocumentNumber indicates an expected call of GetDocumentNumber.
func (mr *MockAccountInterfaceMockRecorder) GetDocumentNumber() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDocumentNumber", reflect.TypeOf((*MockAccountInterface)(nil).GetDocumentNumber))
}

// GetID mocks base method.
func (m *MockAccountInterface) GetID() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(int64)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockAccountInterfaceMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockAccountInterface)(nil).GetID))
}

// IsValid mocks base method.
func (m *MockAccountInterface) IsValid() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsValid")
	ret0, _ := ret[0].(error)
	return ret0
}

// IsValid indicates an expected call of IsValid.
func (mr *MockAccountInterfaceMockRecorder) IsValid() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsValid", reflect.TypeOf((*MockAccountInterface)(nil).IsValid))
}

// SetAmount mocks base method.
func (m *MockAccountInterface) SetAmount(arg0 int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetAmount", arg0)
}

// SetAmount indicates an expected call of SetAmount.
func (mr *MockAccountInterfaceMockRecorder) SetAmount(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAmount", reflect.TypeOf((*MockAccountInterface)(nil).SetAmount), arg0)
}

// SetID mocks base method.
func (m *MockAccountInterface) SetID(arg0 int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetID", arg0)
}

// SetID indicates an expected call of SetID.
func (mr *MockAccountInterfaceMockRecorder) SetID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetID", reflect.TypeOf((*MockAccountInterface)(nil).SetID), arg0)
}
